# Generated by Django 5.2.16 on 2026-08-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attestation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField(unique=True)),
                ("recorded_at", models.DateTimeField()),
                ("status", models.CharField(max_length=16)),
                ("manifest_hash", models.CharField(max_length=64)),
                ("payload", models.JSONField()),
                (
                    "previous_hash",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                (
                    "entry_hash",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
            ],
            options={
                "ordering": ("-sequence",),
            },
        ),
    ]
