# Generated by Django 5.2.16 on 2026-08-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_app", "0003_row_level_security"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="is_organizer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="member",
            name="must_change_password",
            field=models.BooleanField(default=False),
        ),
    ]
