import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Bills of material: MaterialNeed and MaterialGiven.

    Two logs on a project, adjacent and never summed. Nothing here carries a
    value and nothing links to Contribution — see no-material-valuation, which
    fails on a relation to the hours ledger as readily as on a price field.

    RLS clauses generated by kjerne_platform.work.scaffold rather than retyped.
    """

    dependencies = [("site_app", "0009_warehouse")]

    operations = [
        migrations.CreateModel(
            name="MaterialNeed",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False,
                                        primary_key=True, serialize=False)),
                ("description", models.TextField()),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                ("unit", models.CharField(max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("organization", models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="materialneeds", to="site_app.organization")),
                ("project", models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="needs", to="site_app.project")),
                ("added_by", models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="material_needs", to="site_app.member")),
            ],
            options={"ordering": ("created_at",)},
        ),
        migrations.CreateModel(
            name="MaterialGiven",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False,
                                        primary_key=True, serialize=False)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                ("note", models.TextField(blank=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("organization", models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="materialgivens", to="site_app.organization")),
                ("need", models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="given", to="site_app.materialneed")),
                ("member", models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="material_given", to="site_app.member")),
                ("manifest", models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="material_given", to="site_app.manifest")),
            ],
            options={"ordering": ("-recorded_at",)},
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE site_app_materialneed ENABLE ROW LEVEL SECURITY;
            ALTER TABLE site_app_materialneed FORCE ROW LEVEL SECURITY;

            CREATE POLICY tenant_isolation_policy ON site_app_materialneed
                USING (organization_id::text = current_setting('app.current_tenant_id', TRUE));

            CREATE POLICY bypass_rls_policy ON site_app_materialneed
                USING (current_setting('app.bypass_rls', TRUE) = 'on');
            ALTER TABLE site_app_materialgiven ENABLE ROW LEVEL SECURITY;
            ALTER TABLE site_app_materialgiven FORCE ROW LEVEL SECURITY;

            CREATE POLICY tenant_isolation_policy ON site_app_materialgiven
                USING (organization_id::text = current_setting('app.current_tenant_id', TRUE));

            CREATE POLICY bypass_rls_policy ON site_app_materialgiven
                USING (current_setting('app.bypass_rls', TRUE) = 'on');
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS tenant_isolation_policy ON site_app_materialneed;
            DROP POLICY IF EXISTS bypass_rls_policy ON site_app_materialneed;
            ALTER TABLE site_app_materialneed NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE site_app_materialneed DISABLE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenant_isolation_policy ON site_app_materialgiven;
            DROP POLICY IF EXISTS bypass_rls_policy ON site_app_materialgiven;
            ALTER TABLE site_app_materialgiven NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE site_app_materialgiven DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
