import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Comment and Pin. No Thanks model, and no like — see site_app/models.py.

    RLS generated by kjerne_platform.work.scaffold rather than retyped.
    """

    dependencies = [("site_app", "0010_bom")]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False,
                                        primary_key=True, serialize=False)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("organization", models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="comments", to="site_app.organization")),
                ("member", models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="comments", to="site_app.member")),
                ("posting", models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="comments", to="site_app.posting")),
                ("project", models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="comments", to="site_app.project")),
            ],
            options={"ordering": ("created_at",)},
        ),
        migrations.AddConstraint(
            model_name="comment",
            constraint=models.CheckConstraint(
                check=(models.Q(posting__isnull=False, project__isnull=True)
                       | models.Q(posting__isnull=True, project__isnull=False)),
                name="comment_has_exactly_one_parent"),
        ),
        migrations.CreateModel(
            name="Pin",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False,
                                        primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("organization", models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="pins", to="site_app.organization")),
                ("member", models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="pins", to="site_app.member")),
                ("posting", models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="pins", to="site_app.posting")),
                ("project", models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="pins", to="site_app.project")),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddConstraint(
            model_name="pin",
            constraint=models.UniqueConstraint(
                condition=models.Q(posting__isnull=False),
                fields=("member", "posting"), name="one_pin_per_posting"),
        ),
        migrations.AddConstraint(
            model_name="pin",
            constraint=models.UniqueConstraint(
                condition=models.Q(project__isnull=False),
                fields=("member", "project"), name="one_pin_per_project"),
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE site_app_comment ENABLE ROW LEVEL SECURITY;
            ALTER TABLE site_app_comment FORCE ROW LEVEL SECURITY;

            CREATE POLICY tenant_isolation_policy ON site_app_comment
                USING (organization_id::text = current_setting('app.current_tenant_id', TRUE));

            CREATE POLICY bypass_rls_policy ON site_app_comment
                USING (current_setting('app.bypass_rls', TRUE) = 'on');
            ALTER TABLE site_app_pin ENABLE ROW LEVEL SECURITY;
            ALTER TABLE site_app_pin FORCE ROW LEVEL SECURITY;

            CREATE POLICY tenant_isolation_policy ON site_app_pin
                USING (organization_id::text = current_setting('app.current_tenant_id', TRUE));

            CREATE POLICY bypass_rls_policy ON site_app_pin
                USING (current_setting('app.bypass_rls', TRUE) = 'on');
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS tenant_isolation_policy ON site_app_comment;
            DROP POLICY IF EXISTS bypass_rls_policy ON site_app_comment;
            ALTER TABLE site_app_comment NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE site_app_comment DISABLE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenant_isolation_policy ON site_app_pin;
            DROP POLICY IF EXISTS bypass_rls_policy ON site_app_pin;
            ALTER TABLE site_app_pin NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE site_app_pin DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
