# Generated by Django 5.2.16 on 2026-08-11 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Make the migrations say what the models say. Emits no SQL.

    TenantScoped declares related_name="%(class)ss". The migrations for the
    warehouse, bills of material and social models were hand-written to avoid
    an interactive makemigrations prompt, and wrote the RESOLVED names —
    comments, manifests, warehouses. They resolve identically at runtime and
    related_name produces no SQL whatsoever, so nothing was ever broken.

    But the autodetector compares the declared string, so `makemigrations
    --check` failed, which meant it could not be used as a gate and the next
    person to run makemigrations would find a mystery migration mixed in with
    their own. site_app/tests/test_app.py now runs that check.
    """


    dependencies = [
        ("site_app", "0013_member_avatar_colour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="site_app.organization",
            ),
        ),
        migrations.AlterField(
            model_name="manifest",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="site_app.organization",
            ),
        ),
        migrations.AlterField(
            model_name="materialgiven",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="site_app.organization",
            ),
        ),
        migrations.AlterField(
            model_name="materialneed",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="site_app.organization",
            ),
        ),
        migrations.AlterField(
            model_name="pin",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="site_app.organization",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="site_app.organization",
            ),
        ),
        migrations.AlterField(
            model_name="stockline",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="site_app.organization",
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="site_app.organization",
            ),
        ),
    ]
