# Generated by Django 5.2.16 on 2026-08-11 16:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    """Work days and their clearances.

    A work day is announced; a clearance is the record that somebody outside
    the organization said the work could happen. Publication is gated on the
    clearance table and on nothing else -- see WorkDay's docstring for why
    that is not the member gate no-gating removes.

    Clearance carries exactly one Member FK. An earlier draft had two
    (raised_by and obtained_by) and no-exchange refused it on sight.

    RLS clauses follow 0010_bom: ENABLE plus FORCE, so the table owner is
    subject to the policy too, and a missing tenant GUC yields nothing rather
    than everything.
    """


    dependencies = [
        ("site_app", "0014_align_tenant_related_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkDay",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("place", models.TextField()),
                ("muster", models.TextField(blank=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_because", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "called_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_days_called",
                        to="site_app.member",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="site_app.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_days",
                        to="site_app.project",
                    ),
                ),
            ],
            options={
                "ordering": ("starts_at",),
            },
        ),
        migrations.CreateModel(
            name="Clearance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(max_length=120)),
                ("authority", models.TextField()),
                ("obtained_on", models.DateField(blank=True, null=True)),
                ("reference", models.CharField(blank=True, max_length=200)),
                ("note", models.TextField(blank=True)),
                ("expires_on", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="site_app.organization",
                    ),
                ),
                (
                    "raised_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clearances_raised",
                        to="site_app.member",
                    ),
                ),
                (
                    "work_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clearances",
                        to="site_app.workday",
                    ),
                ),
            ],
            options={
                "ordering": ("obtained_on", "created_at"),
            },
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE site_app_workday ENABLE ROW LEVEL SECURITY;
            ALTER TABLE site_app_workday FORCE ROW LEVEL SECURITY;

            CREATE POLICY tenant_isolation_policy ON site_app_workday
                USING (organization_id::text = current_setting('app.current_tenant_id', TRUE));

            CREATE POLICY bypass_rls_policy ON site_app_workday
                USING (current_setting('app.bypass_rls', TRUE) = 'on');

            ALTER TABLE site_app_clearance ENABLE ROW LEVEL SECURITY;
            ALTER TABLE site_app_clearance FORCE ROW LEVEL SECURITY;

            CREATE POLICY tenant_isolation_policy ON site_app_clearance
                USING (organization_id::text = current_setting('app.current_tenant_id', TRUE));

            CREATE POLICY bypass_rls_policy ON site_app_clearance
                USING (current_setting('app.bypass_rls', TRUE) = 'on');
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS tenant_isolation_policy ON site_app_clearance;
            DROP POLICY IF EXISTS bypass_rls_policy ON site_app_clearance;
            ALTER TABLE site_app_clearance NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE site_app_clearance DISABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS tenant_isolation_policy ON site_app_workday;
            DROP POLICY IF EXISTS bypass_rls_policy ON site_app_workday;
            ALTER TABLE site_app_workday NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE site_app_workday DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
