# Generated by Django 5.2.16 on 2026-08-11 17:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Chapters, and the one link from a chapter to a tenant.

    NO ROW-LEVEL SECURITY HERE, AND THAT IS NOT AN OVERSIGHT. RLS in this
    schema keys on organization_id: every tenant-scoped table carries one and
    the policy compares it to the app.current_tenant_id GUC. Region and
    RegionRole have no organization_id because they sit ABOVE organizations,
    exactly as site_app_organization itself does -- which is also not
    protected by RLS, for the same reason.

    What keeps a chapter out of an organization's records is therefore not a
    policy on these tables. It is that neither table can reach tenant data at
    all: no ForeignKey in either direction except Organization.region, which
    points from the tenant to the chapter and cannot be walked backwards into
    anything scoped. test_regions.py asserts that by walking the field list,
    because the shape is the protection.
    """


    dependencies = [
        ("site_app", "0015_workday_clearance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=200)),
                ("covers", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organizations",
                to="site_app.region",
            ),
        ),
        migrations.CreateModel(
            name="RegionRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("lead", "Lead"), ("admin", "Administrator")],
                        default="admin",
                        max_length=8,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="site_app.region",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="region_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("region__name", "role", "created_at"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("region", "user", "role"),
                        name="one_role_per_person_per_region",
                    )
                ],
            },
        ),
    ]
