# Generated by Django 5.2.16 on 2026-08-11 17:44

import kjerne_platform.crypto
from django.db import migrations


class Migration(migrations.Migration):
    """Seal the application-ingress personal data.

    NO DATA MIGRATION, because there were no rows: production held zero
    applications when this ran. Had there been any, they would not have needed
    one either -- kjerne_platform.crypto.decrypt_str returns a non-Fernet
    value unchanged and logs a warning, so a legacy plaintext row reads
    correctly and re-seals itself on the next save. That fallback is a
    migration aid, not a licence to leave rows unsealed.

    The columns widen from 200 to 500 because ciphertext is several times the
    length of its plaintext. The FIELD is not wider; a 200-character legal
    name is still a 200-character legal name.

    What stays plaintext is deliberate: Application.kind, admitted and the
    timestamps, Credential.kind, and Screening.source. Those are what the
    review queries and reports on, and ciphertext does not compare -- a filter
    against an encrypted column matches nothing, silently, forever.
    """


    dependencies = [
        ("site_app", "0017_application_credential_screening"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="contact_name",
            field=kjerne_platform.crypto.EncryptedCharField(
                blank=True, default="", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="decision_note",
            field=kjerne_platform.crypto.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="email",
            field=kjerne_platform.crypto.EncryptedCharField(
                blank=True, default="", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="legal_name",
            field=kjerne_platform.crypto.EncryptedCharField(
                blank=True, default="", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="locality",
            field=kjerne_platform.crypto.EncryptedCharField(
                blank=True, default="", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="phone",
            field=kjerne_platform.crypto.EncryptedCharField(
                blank=True, default="", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="statement",
            field=kjerne_platform.crypto.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name="credential",
            name="authority",
            field=kjerne_platform.crypto.EncryptedCharField(
                blank=True, default="", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="note",
            field=kjerne_platform.crypto.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="credential",
            name="reference",
            field=kjerne_platform.crypto.EncryptedCharField(
                blank=True, default="", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="screening",
            name="note",
            field=kjerne_platform.crypto.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="screening",
            name="searched_name",
            field=kjerne_platform.crypto.EncryptedCharField(
                blank=True, default="", max_length=500
            ),
        ),
    ]
