# Generated by Django 5.2.16 on 2026-08-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_app", "0018_encrypt_application_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="map_areas",
            field=models.TextField(blank=True),
        ),
    ]
