# Generated by Django 5.2.16 on 2026-08-11 22:07

import django.db.models.deletion
import site_app.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    """The impact packet: measures, photos, and the document itself.

    All three are tenant-scoped and carry the usual ENABLE plus FORCE policies.
    A published packet is read by somebody with no session, so that view uses
    bypass_rls deliberately and then re-enters the packet's own tenant -- the
    policy is not relaxed for it.

    Photos land under MEDIA_ROOT, which is routed nowhere. Every photo is
    served by a view that decides whether the requester may have it, because a
    file under a guessable URL is public from the moment it is written.
    """


    dependencies = [
        ("site_app", "0019_region_map_areas"),
    ]

    operations = [
        migrations.CreateModel(
            name="Measure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                ("unit", models.CharField(max_length=40)),
                ("note", models.TextField(blank=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="site_app.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="measures",
                        to="site_app.project",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="measures_recorded",
                        to="site_app.member",
                    ),
                ),
            ],
            options={
                "ordering": ("recorded_at",),
            },
        ),
        migrations.CreateModel(
            name="Packet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField()),
                ("acknowledgements", models.TextField(blank=True)),
                ("token", models.CharField(blank=True, editable=False, max_length=64)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="site_app.organization",
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="packet",
                        to="site_app.project",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="packets_published",
                        to="site_app.member",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.FileField(upload_to=site_app.models._photo_path)),
                ("caption", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="photos_added",
                        to="site_app.member",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="site_app.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="photos",
                        to="site_app.project",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE site_app_measure ENABLE ROW LEVEL SECURITY;
            ALTER TABLE site_app_measure FORCE ROW LEVEL SECURITY;

            CREATE POLICY tenant_isolation_policy ON site_app_measure
                USING (organization_id::text = current_setting('app.current_tenant_id', TRUE));

            CREATE POLICY bypass_rls_policy ON site_app_measure
                USING (current_setting('app.bypass_rls', TRUE) = 'on');

            ALTER TABLE site_app_packet ENABLE ROW LEVEL SECURITY;
            ALTER TABLE site_app_packet FORCE ROW LEVEL SECURITY;

            CREATE POLICY tenant_isolation_policy ON site_app_packet
                USING (organization_id::text = current_setting('app.current_tenant_id', TRUE));

            CREATE POLICY bypass_rls_policy ON site_app_packet
                USING (current_setting('app.bypass_rls', TRUE) = 'on');

            ALTER TABLE site_app_photo ENABLE ROW LEVEL SECURITY;
            ALTER TABLE site_app_photo FORCE ROW LEVEL SECURITY;

            CREATE POLICY tenant_isolation_policy ON site_app_photo
                USING (organization_id::text = current_setting('app.current_tenant_id', TRUE));

            CREATE POLICY bypass_rls_policy ON site_app_photo
                USING (current_setting('app.bypass_rls', TRUE) = 'on');
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS tenant_isolation_policy ON site_app_photo;
            DROP POLICY IF EXISTS bypass_rls_policy ON site_app_photo;
            ALTER TABLE site_app_photo NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE site_app_photo DISABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS tenant_isolation_policy ON site_app_packet;
            DROP POLICY IF EXISTS bypass_rls_policy ON site_app_packet;
            ALTER TABLE site_app_packet NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE site_app_packet DISABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS tenant_isolation_policy ON site_app_measure;
            DROP POLICY IF EXISTS bypass_rls_policy ON site_app_measure;
            ALTER TABLE site_app_measure NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE site_app_measure DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
