# Generated by Django 5.2.16 on 2026-08-11 23:17

import django.db.models.deletion
import kjerne_platform.crypto
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    """Photo consent, chained.

    depicts_people defaults to TRUE, which is the direction this has to fail
    in: a default of False would publish faces by omission on every row that
    existed before anybody thought about it.

    The chain is per organization, like contributions, so one community's
    consent history verifies on its own and a gap shows as a missing sequence.
    """


    dependencies = [
        ("site_app", "0020_impact_packet"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="depicts_people",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="PhotoConsent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "person",
                    kjerne_platform.crypto.EncryptedCharField(
                        blank=True, default="", max_length=500
                    ),
                ),
                ("given_on", models.DateField(blank=True, null=True)),
                ("how", models.CharField(blank=True, max_length=120)),
                ("withdrawn_on", models.DateField(blank=True, null=True)),
                ("note", kjerne_platform.crypto.EncryptedTextField(blank=True)),
                ("recorded_at", models.DateTimeField()),
                ("sequence", models.PositiveIntegerField()),
                (
                    "previous_hash",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                (
                    "entry_hash",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="site_app.organization",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consents",
                        to="site_app.photo",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consents_recorded",
                        to="site_app.member",
                    ),
                ),
            ],
            options={
                "ordering": ("sequence",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "sequence"),
                        name="one_consent_sequence_per_organization",
                    )
                ],
            },
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE site_app_photoconsent ENABLE ROW LEVEL SECURITY;
            ALTER TABLE site_app_photoconsent FORCE ROW LEVEL SECURITY;

            CREATE POLICY tenant_isolation_policy ON site_app_photoconsent
                USING (organization_id::text = current_setting('app.current_tenant_id', TRUE));

            CREATE POLICY bypass_rls_policy ON site_app_photoconsent
                USING (current_setting('app.bypass_rls', TRUE) = 'on');
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS tenant_isolation_policy ON site_app_photoconsent;
            DROP POLICY IF EXISTS bypass_rls_policy ON site_app_photoconsent;
            ALTER TABLE site_app_photoconsent NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE site_app_photoconsent DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
