# Generated by Django 5.2.16 on 2026-08-12 14:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    """Interest: the soft public signal between keeping and committing.

    The policy is the CHAPTER-AWARE one from 0022, not the original
    organization-only clause. A table created after that migration and given
    the old policy would be invisible across the chapter while everything
    beside it was visible — the kind of gap that shows up as one card missing
    a button and nobody knowing why.
    """


    dependencies = [
        ("site_app", "0022_chapter_visibility"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="interests",
                        to="site_app.member",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="site_app.organization",
                    ),
                ),
                (
                    "posting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interests",
                        to="site_app.posting",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("posting", "member"),
                        name="one_interest_per_person_per_posting",
                    )
                ],
            },
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE site_app_interest ENABLE ROW LEVEL SECURITY;
            ALTER TABLE site_app_interest FORCE ROW LEVEL SECURITY;

            CREATE POLICY tenant_isolation_policy ON site_app_interest
                USING (
                    organization_id::text = current_setting('app.current_tenant_id', TRUE)
                    OR (
                        NULLIF(current_setting('app.current_region_id', TRUE), '') IS NOT NULL
                        AND organization_id IN (
                            SELECT id FROM site_app_organization
                            WHERE region_id::text
                                  = current_setting('app.current_region_id', TRUE)
                        )
                    )
                );

            CREATE POLICY bypass_rls_policy ON site_app_interest
                USING (current_setting('app.bypass_rls', TRUE) = 'on');
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS tenant_isolation_policy ON site_app_interest;
            DROP POLICY IF EXISTS bypass_rls_policy ON site_app_interest;
            ALTER TABLE site_app_interest NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE site_app_interest DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
