# Generated by Django 5.2.16 on 2026-08-12 16:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """A record of a removal from a chapter.

    NO ROW-LEVEL SECURITY, for the same reason Region has none: this is about
    the relationship between a chapter and an organization, carries no
    organization_id to key a policy on, and sits above the tenant line
    exactly as site_app_organization does.
    """


    dependencies = [
        ("site_app", "0023_interest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChapterRemoval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.TextField()),
                ("removed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chapter_removals",
                        to="site_app.organization",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="removals",
                        to="site_app.region",
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chapter_removals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-removed_at",),
            },
        ),
    ]
