# Generated by Django 5.2.16 on 2026-08-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    """A third kind of posting: neither asking nor offering.

    A choices= edit is a real migration even though no column changes shape —
    Django records choices in the field's deconstruction, so without this the
    next makemigrations would generate it anyway and the two would drift.

    Nothing is backfilled. Every existing posting stays exactly what it was.
    """


    dependencies = [
        ("site_app", "0025_closed_is_invisible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posting",
            name="kind",
            field=models.CharField(
                choices=[
                    ("offer", "Offering"),
                    ("need", "Need"),
                    ("note", "Just saying"),
                ],
                default="offer",
                max_length=8,
            ),
        ),
    ]
