# Generated by Django 5.2.16 on 2026-08-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_app", "0026_posting_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="public_contact",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="serves",
            field=models.TextField(blank=True),
        ),
    ]
