# Generated by Django 5.2.16 on 2026-08-14 14:15

import django.db.models.deletion
import kjerne_platform.crypto
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_app", "0027_organization_public_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="kind",
            field=models.CharField(
                choices=[
                    ("aid", "Mutual aid group"),
                    ("business", "Business"),
                    ("household", "Household"),
                ],
                default="household",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("need", models.TextField()),
                ("area", models.CharField(blank=True, max_length=120)),
                (
                    "asked_by",
                    kjerne_platform.crypto.EncryptedCharField(
                        blank=True, default="", max_length=500
                    ),
                ),
                ("reach_them", kjerne_platform.crypto.EncryptedTextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("taken_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="site_app.region",
                    ),
                ),
                (
                    "taken_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests_taken",
                        to="site_app.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
