# Generated by Django 5.2.16 on 2026-08-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_app", "0028_organization_kind_and_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="interest",
            name="offered_under",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="posting",
            name="offered_under",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
