# Generated by Django 5.2.16 on 2026-08-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_app", "0029_interest_offered_under_posting_offered_under"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="agreed_terms_version",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
