# Generated by Django 5.2.16 on 2026-08-14 16:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_app", "0030_application_agreed_terms_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attending",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bringing", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attending",
                        to="site_app.workday",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attending",
                        to="site_app.member",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="site_app.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("day", "member"),
                        name="one_attendance_per_person_per_day",
                    )
                ],
            },
        ),
            migrations.RunSQL(
            # Same shape as every other tenant table, including the AND active
            # that 0025 added. A new TenantScoped model without this is
            # readable by every tenant, and nothing in Django would say so —
            # test_rls.py walks the tables and fails on one that is missing.
            sql="""
            ALTER TABLE site_app_attending ENABLE ROW LEVEL SECURITY;
            ALTER TABLE site_app_attending FORCE ROW LEVEL SECURITY;

            CREATE POLICY tenant_isolation_policy ON site_app_attending
                USING (
                    organization_id::text = current_setting('app.current_tenant_id', TRUE)
                    OR (
                        NULLIF(current_setting('app.current_region_id', TRUE), '') IS NOT NULL
                        AND organization_id IN (
                            SELECT id FROM site_app_organization
                            WHERE region_id::text
                                  = current_setting('app.current_region_id', TRUE)
                                  AND active
                        )
                    )
                );

            CREATE POLICY bypass_rls_policy ON site_app_attending
                USING (current_setting('app.bypass_rls', TRUE) = 'on');
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS tenant_isolation_policy ON site_app_attending;
            DROP POLICY IF EXISTS bypass_rls_policy ON site_app_attending;
            ALTER TABLE site_app_attending NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE site_app_attending DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
