from django.urls import path

from . import auth_views, views

app_name = "site_app"

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.member_login, name="login"),
    path("logout/", views.member_logout, name="logout"),
    path("board/", views.board, name="board"),
    path("board/new/", views.posting_new, name="posting_new"),
    path("board/<uuid:posting_id>/", views.posting, name="posting"),
    # The board is the community. Both resolve; the nav points at the name
    # people use, and every existing link and POST target keeps working.
    path("community/", views.board, name="community"),
    path("board/<uuid:posting_id>/claim/", views.claim_posting, name="claim_posting"),
    path("board/<uuid:posting_id>/interested/", views.interested, name="interested"),
    path("request/<uuid:request_id>/", views.request_take, name="request_take"),
    path("board/<uuid:posting_id>/step-off/", views.step_off, name="step_off"),
    path("board/<uuid:posting_id>/close/", views.posting_close, name="posting_close"),
    path("board/<uuid:posting_id>/hours/", views.contribution_new, name="contribution_new"),
    path("ledger/", views.ledger, name="ledger"),
    path("projects/", views.projects, name="projects"),
    path("projects/new/", views.project_new, name="project_new"),
    path("projects/<uuid:project_id>/", views.project_detail, name="project_detail"),
    path("projects/<uuid:project_id>/needs/new/", views.need_new, name="need_new"),
    path("needs/<uuid:need_id>/given/", views.need_given, name="need_given"),
    path("projects/<uuid:project_id>/close/", views.project_close, name="project_close"),
    path("act/<str:token>/", views.act, name="act"),
    path("warehouse/", views.warehouse, name="warehouse"),
    path("warehouse/new/", views.warehouse_new, name="warehouse_new"),
    path("warehouse/<uuid:warehouse_id>/", views.warehouse_detail, name="warehouse_detail"),
    path("warehouse/line/<uuid:line_id>/confirm/", views.stock_confirm, name="stock_confirm"),
    path("warehouse/line/<uuid:line_id>/send/", views.stock_send, name="stock_send"),
    path("manifests/", views.manifests, name="manifests"),
    path("manifest/<uuid:manifest_id>/", views.manifest, name="manifest"),
    path("warehouse/sweep/", views.warehouse_sweep, name="warehouse_sweep"),
    path("comment/", views.comment_new, name="comment_new"),
    path("pin/", views.pin_toggle, name="pin_toggle"),
    path("pinned/", views.pinned, name="pinned"),
    path("you/", views.you, name="you"),
    path("board/<uuid:posting_id>/point/", views.point_at, name="point_at"),
    path("member/<uuid:member_id>/", views.member_page, name="member_page"),
    path("thanks/<uuid:member_id>/", views.thanks, name="thanks"),
    path("pairings/", views.pairings, name="pairings"),
    path("notices/", views.notices, name="notices"),
    path("password/", views.change_password, name="change_password"),
    path("mfa/", auth_views.mfa_challenge, name="mfa_challenge"),
    path("mfa/setup/", auth_views.mfa_setup, name="mfa_setup"),
    path("sso/", auth_views.sso_entry, name="sso_entry"),
    path("setup/<str:token>/", auth_views.setup, name="setup"),
    path("members/", views.members, name="members"),
    path("days/", views.work_days, name="work_days"),
    path("days/new/", views.work_day_new, name="work_day_new"),
    path("days/<uuid:work_day_id>/", views.work_day_detail, name="work_day_detail"),
    path("days/<uuid:work_day_id>/announce/", views.work_day_publish, name="work_day_publish"),
    path("days/<uuid:work_day_id>/off/", views.work_day_cancel, name="work_day_cancel"),
    path("days/clearance/<uuid:clearance_id>/", views.clearance_obtained, name="clearance_obtained"),
    path("members/new/", views.member_new, name="member_new"),
    path("how-it-works/", views.how_it_works, name="how_it_works"),
    path("policy/", views.policy, name="policy"),
    path("need-help/", views.need_help, name="need_help"),
    path("acceptable-use/", views.acceptable_use, name="acceptable_use"),
    path("apply/", views.apply, name="apply"),
    path("chapters/", views.chapters, name="chapters"),
    path("projects/<uuid:project_id>/packet/", views.project_packet, name="project_packet"),
    path("projects/<uuid:project_id>/packet/publish/", views.packet_publish, name="packet_publish"),
    path("packet/<str:token>/", views.packet, name="packet"),
    path("photo/<uuid:photo_id>/", views.packet_photo, name="packet_photo"),
    path("chapter/", views.chapter, name="chapter"),
    path("chapter/remove/<uuid:organization_id>/",
         views.chapter_remove, name="chapter_remove"),
    path("chapter/application/<uuid:application_id>/",
         views.chapter_application, name="chapter_application"),
    path("virtual-warehouse/", views.virtual_warehouse, name="virtual_warehouse"),
    path("attestation/", views.attestation, name="attestation"),
    path("attestation/run/", views.attestation_run, name="attestation_run"),
]
